blank_issues_enabled: true
contact_links:
  - name: Add New Volcano Issue
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/aoiorio/VolcanoAPI/issues/new?template=volcano_issue.md&projects=aoiorio%2FVolcanoAPI%2F1&labels=VolcanoAPI